dist: trusty

sudo: false

language: node_js

node_js:
 - 8.6.0 
 
branches:
  only:
    - master
    
cache:
  bundler: true
  directories:
    - node_modules # NPM packages
    - functions/node_modules

install:
  - npm set progress=false
  - npm i
  - cd functions && npm i ; cd -

script:
  - npm run build

after_success:
  - npm run firebase -- deploy --token $FIREBASE_TOKEN
  - curl https://sentry.io/api/hooks/release/builtin/250533/57e9d53d6937d18ea549071d5fea74d93648961205cbe5e01213946c088b30e8/ -X POST -H 'Content-Type: application/json' -d '{"version": "$TRAVIS_COMMIT"}'