dist: trusty

sudo: false

language: node_js

node_js:
 - 8.6.0 
 
branches:
  only:
    - master
    
cache:
  bundler: true
  directories:
    - node_modules # NPM packages
    - functions/node_modules

install:
  - npm set progress=false
  - npm i
  - cd functions && npm i ; cd -

script:
  - npm run build

before_install:
  - bash ./scripts/version.sh $TRAVIS_COMMIT

after_success:
  - npm run firebase -- deploy --token $FIREBASE_TOKEN
  - bash ./scripts/sentry.sh $SENTRY_TOKEN $TRAVIS_COMMIT